import { AnchorSystemState, ClinicalPhaseInfo, ClinicalPhaseId } from '../types/clinical';

export const INITIAL_PHASES: Record<ClinicalPhaseId, ClinicalPhaseInfo> = {
  1: {
    id: 1,
    name: 'Phase 1: Stabilization & Crisis Management',
    subtitle: 'Impact & Emotional Grounding',
    primaryObjective: 'Stop active damage, enforce complete end of deception, establish emergency safety boundaries.',
    clinicalGate: '100% agreement on safety boundaries; zero new lies for 14 consecutive days.',
    unlockedModuleIds: [2], // Biometrics de-escalation & boundaries
    lockedModuleIds: [1, 3, 4, 5, 6, 7, 8],
    isUnlocked: true,
    isCompleted: false,
  },
  2: {
    id: 2,
    name: 'Phase 2: Truth Reconstruction',
    subtitle: 'Asynchronous Dual-Lock Timeline & Meaning',
    primaryObjective: 'Reconstruct factual history; eliminate piecemeal trickle truth while protecting against graphic trauma triggers.',
    clinicalGate: 'Both partners sign off on the completed written factual timeline and diagnostic question queue.',
    unlockedModuleIds: [1, 2],
    lockedModuleIds: [3, 4, 5, 6, 7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  3: {
    id: 3,
    name: 'Phase 3: Emotional Processing',
    subtitle: 'Attachment Injury & Non-Defensiveness',
    primaryObjective: 'Validate trauma affect; process anger, grief, and fear non-defensively through EFT blamer-softening.',
    clinicalGate: 'Partner B reports feeling deeply heard; Partner A demonstrates zero defensiveness in attunement exercises.',
    unlockedModuleIds: [1, 2, 4],
    lockedModuleIds: [3, 5, 6, 7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  4: {
    id: 4,
    name: 'Phase 4: Behavioral Reconditioning',
    subtitle: 'Operant Consistency & Trust Index',
    primaryObjective: 'Build earned cognitive trust via daily verifiable micro-actions rather than verbal promises.',
    clinicalGate: '60 consecutive days with >95% Behavioral Consistency Index (BCI).',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [6, 7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  5: {
    id: 5,
    name: 'Phase 5: Communication Repair',
    subtitle: 'Gottman Sound House & Conflict De-escalation',
    primaryObjective: 'Eliminate Gottman’s Four Horsemen (Criticism, Contempt, Defensiveness, Stonewalling).',
    clinicalGate: 'Successful completion of 3 un-flooded conflict discussions.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [6, 7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  6: {
    id: 6,
    name: 'Phase 6: Shared Meaning & Connection',
    subtitle: 'Relational Redefinition & Positive Rituals',
    primaryObjective: 'Rebuild dyadic cohesion and shared positive experiences.',
    clinicalGate: 'Statistically significant improvement in Dyadic Adjustment (RDAS) score.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  7: {
    id: 7,
    name: 'Phase 7: Vulnerability & Intimacy',
    subtitle: 'Sensate Focus & Deep Re-attachment',
    primaryObjective: 'Safely restore emotional vulnerability and consensual physical connection.',
    clinicalGate: 'Mutual agreement on emotional safety prior to physical intimacy exercises.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [8],
    isUnlocked: false,
    isCompleted: false,
  },
  8: {
    id: 8,
    name: 'Phase 8: Long-Term Maintenance & Sunset',
    subtitle: 'Surveillance Sunset & Relapse Prevention',
    primaryObjective: 'Phase out surveillance scaffolding; establish permanent internal trust & relapse prevention plans.',
    clinicalGate: 'Graduation to maintenance mode; digital checking fully decommissioned.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [],
    isUnlocked: false,
    isCompleted: false,
  },
};

export const INITIAL_SYSTEM_STATE: AnchorSystemState = {
  version: 1,
  lobby: {
    lobbyCode: 'ANCHOR-7X9K',
    coupleName: '',
    createdDate: '',
    partnerA_Online: false,
    partnerB_Online: false,
    partnerA_ReadyForSession: false,
    partnerB_ReadyForSession: false,
    activeSyncStatus: 'offline',
    lastSyncTimestamp: 0,
  },
  activeRole: 'partnerB', // Default to Injured Partner perspective
  currentPhase: 1, // Start at Phase 1
  phases: INITIAL_PHASES,
  triage: {
    completed: false, // Intake not completed on first load
    screenDate: '',
    ipvFlag: false,
    coerciveControlFlag: false,
    activeDeceptionFlag: false,
    activeAddictionFlag: false,
    hardStopActive: false,
    safetyPlanAcknowledged: false,
  },
  timeline: {
    sessionActive: false,
    dualLockUnlocked: false,
    entries: [],
    questions: [],
  },
  biometrics: {
    currentHeartRate: 72,
    currentHRV: 60,
    isFlooded: false,
    floodingTriggeredBy: null,
    lockoutRemainingSeconds: 0,
    lockoutTotalSeconds: 1200,
    partnerA_Regulated: true,
    partnerB_Regulated: true,
    groundingExerciseCompleted: true,
  },
  commitments: [],
  attunementChat: [],
  transparency: {
    logs: [],
    sunset: {
      lastEvaluationDate: '',
      nextEvaluationDate: '',
      consistencyScore: 0,
      minimumDaysMaintained: 0,
      eligibleForDecommissioning: false,
      decommissionApprovedByPartnerA: false,
      decommissionApprovedByPartnerB: false,
      isMonitoringDecommissioned: false,
    },
  },
  psychometrics: [],
};
