import { AnchorSystemState, ClinicalPhaseInfo, ClinicalPhaseId } from '../types/clinical';

export const INITIAL_PHASES: Record<ClinicalPhaseId, ClinicalPhaseInfo> = {
  1: {
    id: 1,
    name: 'Phase 1: Stabilization & Crisis Management',
    subtitle: 'Impact & Emotional Grounding',
    primaryObjective: 'Stop active damage, enforce complete end of deception, establish emergency safety boundaries.',
    clinicalGate: '100% agreement on safety boundaries; zero new lies for 14 consecutive days.',
    unlockedModuleIds: [2], // Biometrics de-escalation & boundaries
    lockedModuleIds: [1, 3, 4, 5, 6, 7, 8],
    isUnlocked: true,
    isCompleted: true,
    completionDate: '2026-07-28',
  },
  2: {
    id: 2,
    name: 'Phase 2: Truth Reconstruction',
    subtitle: 'Asynchronous Dual-Lock Timeline & Meaning',
    primaryObjective: 'Reconstruct factual history; eliminate piecemeal trickle truth while protecting against graphic trauma triggers.',
    clinicalGate: 'Both partners sign off on the completed written factual timeline and diagnostic question queue.',
    unlockedModuleIds: [1, 2],
    lockedModuleIds: [3, 4, 5, 6, 7, 8],
    isUnlocked: true,
    isCompleted: true,
    completionDate: '2026-08-04',
  },
  3: {
    id: 3,
    name: 'Phase 3: Emotional Processing',
    subtitle: 'Attachment Injury & Non-Defensiveness',
    primaryObjective: 'Validate trauma affect; process anger, grief, and fear non-defensively through EFT blamer-softening.',
    clinicalGate: 'Partner B reports feeling deeply heard; Partner A demonstrates zero defensiveness in attunement exercises.',
    unlockedModuleIds: [1, 2, 4],
    lockedModuleIds: [3, 5, 6, 7, 8],
    isUnlocked: true,
    isCompleted: true,
    completionDate: '2026-08-10',
  },
  4: {
    id: 4,
    name: 'Phase 4: Behavioral Reconditioning',
    subtitle: 'Operant Consistency & Trust Index',
    primaryObjective: 'Build earned cognitive trust via daily verifiable micro-actions rather than verbal promises.',
    clinicalGate: '60 consecutive days with >95% Behavioral Consistency Index (BCI).',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [6, 7, 8],
    isUnlocked: true,
    isCompleted: false,
  },
  5: {
    id: 5,
    name: 'Phase 5: Communication Repair',
    subtitle: 'Gottman Sound House & Conflict De-escalation',
    primaryObjective: 'Eliminate Gottman’s Four Horsemen (Criticism, Contempt, Defensiveness, Stonewalling).',
    clinicalGate: 'Successful completion of 3 un-flooded conflict discussions.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [6, 7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  6: {
    id: 6,
    name: 'Phase 6: Shared Meaning & Connection',
    subtitle: 'Relational Redefinition & Positive Rituals',
    primaryObjective: 'Rebuild dyadic cohesion and shared positive experiences.',
    clinicalGate: 'Statistically significant improvement in Dyadic Adjustment (RDAS) score.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [7, 8],
    isUnlocked: false,
    isCompleted: false,
  },
  7: {
    id: 7,
    name: 'Phase 7: Vulnerability & Intimacy',
    subtitle: 'Sensate Focus & Deep Re-attachment',
    primaryObjective: 'Safely restore emotional vulnerability and consensual physical connection.',
    clinicalGate: 'Mutual agreement on emotional safety prior to physical intimacy exercises.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [8],
    isUnlocked: false,
    isCompleted: false,
  },
  8: {
    id: 8,
    name: 'Phase 8: Long-Term Maintenance & Sunset',
    subtitle: 'Surveillance Sunset & Relapse Prevention',
    primaryObjective: 'Phase out surveillance scaffolding; establish permanent internal trust & relapse prevention plans.',
    clinicalGate: 'Graduation to maintenance mode; digital checking fully decommissioned.',
    unlockedModuleIds: [1, 2, 3, 4, 5],
    lockedModuleIds: [],
    isUnlocked: false,
    isCompleted: false,
  },
};

export const INITIAL_SYSTEM_STATE: AnchorSystemState = {
  version: 1,
  lobby: {
    lobbyCode: 'ANCHOR-7X9K',
    coupleName: 'Alex & Jordan',
    createdDate: '2026-07-15',
    partnerA_Online: true,
    partnerB_Online: true,
    partnerA_ReadyForSession: false,
    partnerB_ReadyForSession: false,
    activeSyncStatus: 'synced',
    lastSyncTimestamp: Date.now(),
  },
  activeRole: 'partnerB', // Default to Injured Partner perspective
  currentPhase: 4, // In Behavioral Reconditioning
  phases: INITIAL_PHASES,
  triage: {
    completed: true,
    screenDate: '2026-07-15',
    ipvFlag: false,
    coerciveControlFlag: false,
    activeDeceptionFlag: false,
    activeAddictionFlag: false,
    hardStopActive: false,
    safetyPlanAcknowledged: true,
  },
  timeline: {
    sessionActive: false,
    dualLockUnlocked: true,
    entries: [
      {
        id: 't-1',
        date: '2026-05-12',
        title: 'Initial Hidden Communications via Messaging App',
        category: 'digital_messaging',
        factualDescription: 'Began direct messaging with former coworker on encrypted app without disclosing the contact.',
        financialScope: '$0.00',
        locationScope: 'Home / Remote',
        status: 'disclosed_and_reviewed',
        partnerA_Signed: true,
        partnerB_Acknowledged: true,
        createdAt: '2026-07-20T14:30:00Z',
      },
      {
        id: 't-2',
        date: '2026-06-03',
        title: 'In-Person Dinner Meeting Under Pretext of Overtime',
        category: 'direct_contact',
        factualDescription: 'Met for private dinner at downtown bistro while stating I was working late at the office.',
        financialScope: '$148.50 on personal credit card',
        locationScope: 'Downtown Bistro, 4th Street',
        status: 'disclosed_and_reviewed',
        partnerA_Signed: true,
        partnerB_Acknowledged: true,
        createdAt: '2026-07-22T09:15:00Z',
      },
      {
        id: 't-3',
        date: '2026-06-28',
        title: 'Hotel Booking for Weekend Conference',
        category: 'financial_expenditure',
        factualDescription: 'Reserved individual room during regional seminar where unplanned contact occurred.',
        financialScope: '$340.00 reimbursed through personal funds',
        locationScope: 'Grand Hyatt Metro',
        status: 'disclosed_and_reviewed',
        partnerA_Signed: true,
        partnerB_Acknowledged: true,
        createdAt: '2026-07-25T11:00:00Z',
      },
    ],
    questions: [
      {
        id: 'q-1',
        question: 'Were any joint marital funds or savings accounts used during this period?',
        clinicalIntent: 'financial_impact',
        isAnswered: true,
        answerText: 'No. All expenditures were made on my personal separate credit card ($488.50 total), and no marital bank accounts were accessed.',
        answeredAt: '2026-07-26T16:00:00Z',
        createdAt: '2026-07-21T18:00:00Z',
      },
      {
        id: 'q-2',
        question: 'Has all contact been definitively terminated, and what steps were taken to ensure no future reaching out occurs?',
        clinicalIntent: 'boundary_reassurance',
        isAnswered: true,
        answerText: 'All phone numbers, social media profiles, and communication channels have been permanently blocked in front of individual therapist on July 16.',
        answeredAt: '2026-07-27T10:30:00Z',
        createdAt: '2026-07-21T18:05:00Z',
      },
    ],
  },
  biometrics: {
    currentHeartRate: 72,
    currentHRV: 58,
    isFlooded: false,
    floodingTriggeredBy: null,
    lockoutRemainingSeconds: 0,
    lockoutTotalSeconds: 1200, // 20 minutes (1200s)
    partnerA_Regulated: true,
    partnerB_Regulated: true,
    groundingExerciseCompleted: true,
  },
  commitments: [
    {
      id: 'c-1',
      title: 'Daily Mid-Day Video Check-in',
      category: 'communication',
      dueTime: '12:30 PM',
      targetDate: '2026-08-14',
      completed: true,
      verifiedByPartnerB: true,
      proofType: 'timestamp',
      proofDetail: 'Connected at 12:28 PM for 8-min check-in from office desk',
      completedAt: '2026-08-14T12:30:00Z',
    },
    {
      id: 'c-2',
      title: 'Upload Lunch Meeting Itemized Receipt',
      category: 'financial',
      dueTime: '2:30 PM',
      targetDate: '2026-08-14',
      completed: true,
      verifiedByPartnerB: true,
      proofType: 'receipt_upload',
      proofDetail: 'Receipt #88219 - Client lunch ($32.40) at Corner Cafe',
      completedAt: '2026-08-14T14:15:00Z',
    },
    {
      id: 'c-3',
      title: 'Evening Departure Departure Time Confirmation',
      category: 'schedule',
      dueTime: '5:15 PM',
      targetDate: '2026-08-14',
      completed: false,
      verifiedByPartnerB: false,
      proofType: 'location_checkin',
      proofDetail: 'Pending evening check-in',
    },
    {
      id: 'c-4',
      title: 'Attunement Reflection Exercise Journaling',
      category: 'relational_care',
      dueTime: '8:30 PM',
      targetDate: '2026-08-14',
      completed: false,
      verifiedByPartnerB: false,
      proofType: 'self_verified',
    },
  ],
  attunementChat: [
    {
      id: 'msg-1',
      senderRole: 'partnerB',
      rawText: 'I still have moments where an intrusive wave of anxiety hits me when your phone lights up.',
      intercepted: false,
      finalSentText: 'I still have moments where an intrusive wave of anxiety hits me when your phone lights up.',
      timestamp: '2026-08-14T10:15:00Z',
      validationScore: 90,
    },
    {
      id: 'msg-2',
      senderRole: 'partnerA',
      rawText: 'I hear how much anxiety that causes you. You have every right to feel guarded, and I am leaving my phone face up on the counter with notifications open whenever we are home.',
      intercepted: false,
      finalSentText: 'I hear how much anxiety that causes you. You have every right to feel guarded, and I am leaving my phone face up on the counter with notifications open whenever we are home.',
      timestamp: '2026-08-14T10:18:00Z',
      validationScore: 98,
    },
  ],
  transparency: {
    logs: [
      {
        id: 'log-1',
        type: 'schedule',
        summary: 'Arrival at Downtown Office',
        detail: 'Logged arrival at Building B, 4th floor at 8:45 AM',
        timestamp: '2026-08-14T08:45:00Z',
        voluntary: true,
      },
      {
        id: 'log-2',
        type: 'financial',
        summary: 'Coffee & Parking Transaction',
        detail: 'Card charge: $4.50 (Coffee) + $12.00 (Metro Garage)',
        timestamp: '2026-08-14T09:05:00Z',
        voluntary: true,
      },
      {
        id: 'log-3',
        type: 'location',
        summary: 'Scheduled Client Onsite Meeting',
        detail: 'Departing for TechPark Suite 200 from 1:30 PM to 3:00 PM',
        timestamp: '2026-08-14T13:20:00Z',
        voluntary: true,
      },
    ],
    sunset: {
      lastEvaluationDate: '2026-08-01',
      nextEvaluationDate: '2026-08-31',
      consistencyScore: 97.2,
      minimumDaysMaintained: 45,
      eligibleForDecommissioning: true,
      decommissionApprovedByPartnerA: false,
      decommissionApprovedByPartnerB: false,
      isMonitoringDecommissioned: false,
    },
  },
  psychometrics: [
    { assessmentDate: '2026-07-15', dayNumber: 1, dtsScore: 18, rdasScore: 28, perceivedSafetyScore: 12, partnerARating: 45, partnerBRating: 15 },
    { assessmentDate: '2026-07-22', dayNumber: 7, dtsScore: 26, rdasScore: 35, perceivedSafetyScore: 24, partnerARating: 52, partnerBRating: 25 },
    { assessmentDate: '2026-07-29', dayNumber: 14, dtsScore: 42, rdasScore: 48, perceivedSafetyScore: 40, partnerARating: 65, partnerBRating: 42 },
    { assessmentDate: '2026-08-05', dayNumber: 21, dtsScore: 61, rdasScore: 62, perceivedSafetyScore: 58, partnerARating: 78, partnerBRating: 60 },
    { assessmentDate: '2026-08-12', dayNumber: 28, dtsScore: 78, rdasScore: 76, perceivedSafetyScore: 74, partnerARating: 86, partnerBRating: 75 },
  ],
};
